// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: ztm/v1/gossip.proto

package ztmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeStatus int32

const (
	NodeStatus_NODE_STATUS_UNSPECIFIED NodeStatus = 0
	NodeStatus_NODE_STATUS_ALIVE       NodeStatus = 1
	NodeStatus_NODE_STATUS_SUSPECT     NodeStatus = 2
	NodeStatus_NODE_STATUS_DEAD        NodeStatus = 3
)

// Enum value maps for NodeStatus.
var (
	NodeStatus_name = map[int32]string{
		0: "NODE_STATUS_UNSPECIFIED",
		1: "NODE_STATUS_ALIVE",
		2: "NODE_STATUS_SUSPECT",
		3: "NODE_STATUS_DEAD",
	}
	NodeStatus_value = map[string]int32{
		"NODE_STATUS_UNSPECIFIED": 0,
		"NODE_STATUS_ALIVE":       1,
		"NODE_STATUS_SUSPECT":     2,
		"NODE_STATUS_DEAD":        3,
	}
)

func (x NodeStatus) Enum() *NodeStatus {
	p := new(NodeStatus)
	*p = x
	return p
}

func (x NodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_ztm_v1_gossip_proto_enumTypes[0].Descriptor()
}

func (NodeStatus) Type() protoreflect.EnumType {
	return &file_ztm_v1_gossip_proto_enumTypes[0]
}

func (x NodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeStatus.Descriptor instead.
func (NodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_ztm_v1_gossip_proto_rawDescGZIP(), []int{0}
}

type GossipType int32

const (
	GossipType_GOSSIP_TYPE_UNSPECIFIED      GossipType = 0
	GossipType_GOSSIP_TYPE_NODE_STATE       GossipType = 1
	GossipType_GOSSIP_TYPE_SERVICE_ANNOUNCE GossipType = 2
	GossipType_GOSSIP_TYPE_POLICY_BUNDLE    GossipType = 3
)

// Enum value maps for GossipType.
var (
	GossipType_name = map[int32]string{
		0: "GOSSIP_TYPE_UNSPECIFIED",
		1: "GOSSIP_TYPE_NODE_STATE",
		2: "GOSSIP_TYPE_SERVICE_ANNOUNCE",
		3: "GOSSIP_TYPE_POLICY_BUNDLE",
	}
	GossipType_value = map[string]int32{
		"GOSSIP_TYPE_UNSPECIFIED":      0,
		"GOSSIP_TYPE_NODE_STATE":       1,
		"GOSSIP_TYPE_SERVICE_ANNOUNCE": 2,
		"GOSSIP_TYPE_POLICY_BUNDLE":    3,
	}
)

func (x GossipType) Enum() *GossipType {
	p := new(GossipType)
	*p = x
	return p
}

func (x GossipType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GossipType) Descriptor() protoreflect.EnumDescriptor {
	return file_ztm_v1_gossip_proto_enumTypes[1].Descriptor()
}

func (GossipType) Type() protoreflect.EnumType {
	return &file_ztm_v1_gossip_proto_enumTypes[1]
}

func (x GossipType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GossipType.Descriptor instead.
func (GossipType) EnumDescriptor() ([]byte, []int) {
	return file_ztm_v1_gossip_proto_rawDescGZIP(), []int{1}
}

type Endpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"` // "tcp", "udp"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_ztm_v1_gossip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_ztm_v1_gossip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_ztm_v1_gossip_proto_rawDescGZIP(), []int{0}
}

func (x *Endpoint) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Endpoint) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Endpoint) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type NodeState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	MeshAddr      string                 `protobuf:"bytes,2,opt,name=mesh_addr,json=meshAddr,proto3" json:"mesh_addr,omitempty"`
	ClientAddr    string                 `protobuf:"bytes,3,opt,name=client_addr,json=clientAddr,proto3" json:"client_addr,omitempty"`
	Incarnation   uint64                 `protobuf:"varint,4,opt,name=incarnation,proto3" json:"incarnation,omitempty"`
	Status        NodeStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=ztm.v1.NodeStatus" json:"status,omitempty"`
	Capabilities  []string               `protobuf:"bytes,6,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	UpdatedAtUnix int64                  `protobuf:"varint,7,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeState) Reset() {
	*x = NodeState{}
	mi := &file_ztm_v1_gossip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeState) ProtoMessage() {}

func (x *NodeState) ProtoReflect() protoreflect.Message {
	mi := &file_ztm_v1_gossip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeState.ProtoReflect.Descriptor instead.
func (*NodeState) Descriptor() ([]byte, []int) {
	return file_ztm_v1_gossip_proto_rawDescGZIP(), []int{1}
}

func (x *NodeState) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeState) GetMeshAddr() string {
	if x != nil {
		return x.MeshAddr
	}
	return ""
}

func (x *NodeState) GetClientAddr() string {
	if x != nil {
		return x.ClientAddr
	}
	return ""
}

func (x *NodeState) GetIncarnation() uint64 {
	if x != nil {
		return x.Incarnation
	}
	return 0
}

func (x *NodeState) GetStatus() NodeStatus {
	if x != nil {
		return x.Status
	}
	return NodeStatus_NODE_STATUS_UNSPECIFIED
}

func (x *NodeState) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *NodeState) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

type GossipEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cluster       string                 `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Type          GossipType             `protobuf:"varint,2,opt,name=type,proto3,enum=ztm.v1.GossipType" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature     []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipEnvelope) Reset() {
	*x = GossipEnvelope{}
	mi := &file_ztm_v1_gossip_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipEnvelope) ProtoMessage() {}

func (x *GossipEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_ztm_v1_gossip_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipEnvelope.ProtoReflect.Descriptor instead.
func (*GossipEnvelope) Descriptor() ([]byte, []int) {
	return file_ztm_v1_gossip_proto_rawDescGZIP(), []int{2}
}

func (x *GossipEnvelope) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *GossipEnvelope) GetType() GossipType {
	if x != nil {
		return x.Type
	}
	return GossipType_GOSSIP_TYPE_UNSPECIFIED
}

func (x *GossipEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GossipEnvelope) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type ServiceAnnouncement struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServiceId       string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	NodeId          string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Endpoints       []*Endpoint            `protobuf:"bytes,4,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Labels          map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Version         uint64                 `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	TtlSec          int64                  `protobuf:"varint,7,opt,name=ttl_sec,json=ttlSec,proto3" json:"ttl_sec,omitempty"`
	AnnouncedAtUnix int64                  `protobuf:"varint,8,opt,name=announced_at_unix,json=announcedAtUnix,proto3" json:"announced_at_unix,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServiceAnnouncement) Reset() {
	*x = ServiceAnnouncement{}
	mi := &file_ztm_v1_gossip_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceAnnouncement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceAnnouncement) ProtoMessage() {}

func (x *ServiceAnnouncement) ProtoReflect() protoreflect.Message {
	mi := &file_ztm_v1_gossip_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceAnnouncement.ProtoReflect.Descriptor instead.
func (*ServiceAnnouncement) Descriptor() ([]byte, []int) {
	return file_ztm_v1_gossip_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceAnnouncement) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ServiceAnnouncement) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ServiceAnnouncement) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceAnnouncement) GetEndpoints() []*Endpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *ServiceAnnouncement) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ServiceAnnouncement) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ServiceAnnouncement) GetTtlSec() int64 {
	if x != nil {
		return x.TtlSec
	}
	return 0
}

func (x *ServiceAnnouncement) GetAnnouncedAtUnix() int64 {
	if x != nil {
		return x.AnnouncedAtUnix
	}
	return 0
}

var File_ztm_v1_gossip_proto protoreflect.FileDescriptor

const file_ztm_v1_gossip_proto_rawDesc = "" +
	"\n" +
	"\x13ztm/v1/gossip.proto\x12\x06ztm.v1\"N\n" +
	"\bEndpoint\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\"\xfc\x01\n" +
	"\tNodeState\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tmesh_addr\x18\x02 \x01(\tR\bmeshAddr\x12\x1f\n" +
	"\vclient_addr\x18\x03 \x01(\tR\n" +
	"clientAddr\x12 \n" +
	"\vincarnation\x18\x04 \x01(\x04R\vincarnation\x12*\n" +
	"\x06status\x18\x05 \x01(\x0e2\x12.ztm.v1.NodeStatusR\x06status\x12\"\n" +
	"\fcapabilities\x18\x06 \x03(\tR\fcapabilities\x12&\n" +
	"\x0fupdated_at_unix\x18\a \x01(\x03R\rupdatedAtUnix\"\x8a\x01\n" +
	"\x0eGossipEnvelope\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12&\n" +
	"\x04type\x18\x02 \x01(\x0e2\x12.ztm.v1.GossipTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\"\xec\x02\n" +
	"\x13ServiceAnnouncement\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12.\n" +
	"\tendpoints\x18\x04 \x03(\v2\x10.ztm.v1.EndpointR\tendpoints\x12?\n" +
	"\x06labels\x18\x05 \x03(\v2'.ztm.v1.ServiceAnnouncement.LabelsEntryR\x06labels\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x04R\aversion\x12\x17\n" +
	"\attl_sec\x18\a \x01(\x03R\x06ttlSec\x12*\n" +
	"\x11announced_at_unix\x18\b \x01(\x03R\x0fannouncedAtUnix\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*o\n" +
	"\n" +
	"NodeStatus\x12\x1b\n" +
	"\x17NODE_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11NODE_STATUS_ALIVE\x10\x01\x12\x17\n" +
	"\x13NODE_STATUS_SUSPECT\x10\x02\x12\x14\n" +
	"\x10NODE_STATUS_DEAD\x10\x03*\x86\x01\n" +
	"\n" +
	"GossipType\x12\x1b\n" +
	"\x17GOSSIP_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16GOSSIP_TYPE_NODE_STATE\x10\x01\x12 \n" +
	"\x1cGOSSIP_TYPE_SERVICE_ANNOUNCE\x10\x02\x12\x1d\n" +
	"\x19GOSSIP_TYPE_POLICY_BUNDLE\x10\x03B\x1cZ\x1aztm/api/proto/ztm/v1;ztmv1b\x06proto3"

var (
	file_ztm_v1_gossip_proto_rawDescOnce sync.Once
	file_ztm_v1_gossip_proto_rawDescData []byte
)

func file_ztm_v1_gossip_proto_rawDescGZIP() []byte {
	file_ztm_v1_gossip_proto_rawDescOnce.Do(func() {
		file_ztm_v1_gossip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ztm_v1_gossip_proto_rawDesc), len(file_ztm_v1_gossip_proto_rawDesc)))
	})
	return file_ztm_v1_gossip_proto_rawDescData
}

var file_ztm_v1_gossip_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ztm_v1_gossip_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ztm_v1_gossip_proto_goTypes = []any{
	(NodeStatus)(0),             // 0: ztm.v1.NodeStatus
	(GossipType)(0),             // 1: ztm.v1.GossipType
	(*Endpoint)(nil),            // 2: ztm.v1.Endpoint
	(*NodeState)(nil),           // 3: ztm.v1.NodeState
	(*GossipEnvelope)(nil),      // 4: ztm.v1.GossipEnvelope
	(*ServiceAnnouncement)(nil), // 5: ztm.v1.ServiceAnnouncement
	nil,                         // 6: ztm.v1.ServiceAnnouncement.LabelsEntry
}
var file_ztm_v1_gossip_proto_depIdxs = []int32{
	0, // 0: ztm.v1.NodeState.status:type_name -> ztm.v1.NodeStatus
	1, // 1: ztm.v1.GossipEnvelope.type:type_name -> ztm.v1.GossipType
	2, // 2: ztm.v1.ServiceAnnouncement.endpoints:type_name -> ztm.v1.Endpoint
	6, // 3: ztm.v1.ServiceAnnouncement.labels:type_name -> ztm.v1.ServiceAnnouncement.LabelsEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ztm_v1_gossip_proto_init() }
func file_ztm_v1_gossip_proto_init() {
	if File_ztm_v1_gossip_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ztm_v1_gossip_proto_rawDesc), len(file_ztm_v1_gossip_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ztm_v1_gossip_proto_goTypes,
		DependencyIndexes: file_ztm_v1_gossip_proto_depIdxs,
		EnumInfos:         file_ztm_v1_gossip_proto_enumTypes,
		MessageInfos:      file_ztm_v1_gossip_proto_msgTypes,
	}.Build()
	File_ztm_v1_gossip_proto = out.File
	file_ztm_v1_gossip_proto_goTypes = nil
	file_ztm_v1_gossip_proto_depIdxs = nil
}
