// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: ztm/v1/policy.proto

package ztmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PolicyRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Allow         []*PolicyMatch         `protobuf:"bytes,2,rep,name=allow,proto3" json:"allow,omitempty"`
	Deny          []*PolicyMatch         `protobuf:"bytes,3,rep,name=deny,proto3" json:"deny,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyRule) Reset() {
	*x = PolicyRule{}
	mi := &file_ztm_v1_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyRule) ProtoMessage() {}

func (x *PolicyRule) ProtoReflect() protoreflect.Message {
	mi := &file_ztm_v1_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyRule.ProtoReflect.Descriptor instead.
func (*PolicyRule) Descriptor() ([]byte, []int) {
	return file_ztm_v1_policy_proto_rawDescGZIP(), []int{0}
}

func (x *PolicyRule) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *PolicyRule) GetAllow() []*PolicyMatch {
	if x != nil {
		return x.Allow
	}
	return nil
}

func (x *PolicyRule) GetDeny() []*PolicyMatch {
	if x != nil {
		return x.Deny
	}
	return nil
}

type PolicyMatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Target:
	//
	//	*PolicyMatch_Service
	//	*PolicyMatch_Relay
	Target        isPolicyMatch_Target `protobuf_oneof:"target"`
	Ports         []uint32             `protobuf:"varint,3,rep,packed,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyMatch) Reset() {
	*x = PolicyMatch{}
	mi := &file_ztm_v1_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyMatch) ProtoMessage() {}

func (x *PolicyMatch) ProtoReflect() protoreflect.Message {
	mi := &file_ztm_v1_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyMatch.ProtoReflect.Descriptor instead.
func (*PolicyMatch) Descriptor() ([]byte, []int) {
	return file_ztm_v1_policy_proto_rawDescGZIP(), []int{1}
}

func (x *PolicyMatch) GetTarget() isPolicyMatch_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *PolicyMatch) GetService() string {
	if x != nil {
		if x, ok := x.Target.(*PolicyMatch_Service); ok {
			return x.Service
		}
	}
	return ""
}

func (x *PolicyMatch) GetRelay() string {
	if x != nil {
		if x, ok := x.Target.(*PolicyMatch_Relay); ok {
			return x.Relay
		}
	}
	return ""
}

func (x *PolicyMatch) GetPorts() []uint32 {
	if x != nil {
		return x.Ports
	}
	return nil
}

type isPolicyMatch_Target interface {
	isPolicyMatch_Target()
}

type PolicyMatch_Service struct {
	Service string `protobuf:"bytes,1,opt,name=service,proto3,oneof"`
}

type PolicyMatch_Relay struct {
	Relay string `protobuf:"bytes,2,opt,name=relay,proto3,oneof"`
}

func (*PolicyMatch_Service) isPolicyMatch_Target() {}

func (*PolicyMatch_Relay) isPolicyMatch_Target() {}

type PolicyBundle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Cluster       string                 `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Rules         []*PolicyRule          `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	UpdatedAtUnix int64                  `protobuf:"varint,4,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyBundle) Reset() {
	*x = PolicyBundle{}
	mi := &file_ztm_v1_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyBundle) ProtoMessage() {}

func (x *PolicyBundle) ProtoReflect() protoreflect.Message {
	mi := &file_ztm_v1_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyBundle.ProtoReflect.Descriptor instead.
func (*PolicyBundle) Descriptor() ([]byte, []int) {
	return file_ztm_v1_policy_proto_rawDescGZIP(), []int{2}
}

func (x *PolicyBundle) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PolicyBundle) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *PolicyBundle) GetRules() []*PolicyRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *PolicyBundle) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

var File_ztm_v1_policy_proto protoreflect.FileDescriptor

const file_ztm_v1_policy_proto_rawDesc = "" +
	"\n" +
	"\x13ztm/v1/policy.proto\x12\x06ztm.v1\"z\n" +
	"\n" +
	"PolicyRule\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12)\n" +
	"\x05allow\x18\x02 \x03(\v2\x13.ztm.v1.PolicyMatchR\x05allow\x12'\n" +
	"\x04deny\x18\x03 \x03(\v2\x13.ztm.v1.PolicyMatchR\x04deny\"a\n" +
	"\vPolicyMatch\x12\x1a\n" +
	"\aservice\x18\x01 \x01(\tH\x00R\aservice\x12\x16\n" +
	"\x05relay\x18\x02 \x01(\tH\x00R\x05relay\x12\x14\n" +
	"\x05ports\x18\x03 \x03(\rR\x05portsB\b\n" +
	"\x06target\"\x94\x01\n" +
	"\fPolicyBundle\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12\x18\n" +
	"\acluster\x18\x02 \x01(\tR\acluster\x12(\n" +
	"\x05rules\x18\x03 \x03(\v2\x12.ztm.v1.PolicyRuleR\x05rules\x12&\n" +
	"\x0fupdated_at_unix\x18\x04 \x01(\x03R\rupdatedAtUnixB\x1cZ\x1aztm/api/proto/ztm/v1;ztmv1b\x06proto3"

var (
	file_ztm_v1_policy_proto_rawDescOnce sync.Once
	file_ztm_v1_policy_proto_rawDescData []byte
)

func file_ztm_v1_policy_proto_rawDescGZIP() []byte {
	file_ztm_v1_policy_proto_rawDescOnce.Do(func() {
		file_ztm_v1_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ztm_v1_policy_proto_rawDesc), len(file_ztm_v1_policy_proto_rawDesc)))
	})
	return file_ztm_v1_policy_proto_rawDescData
}

var file_ztm_v1_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ztm_v1_policy_proto_goTypes = []any{
	(*PolicyRule)(nil),   // 0: ztm.v1.PolicyRule
	(*PolicyMatch)(nil),  // 1: ztm.v1.PolicyMatch
	(*PolicyBundle)(nil), // 2: ztm.v1.PolicyBundle
}
var file_ztm_v1_policy_proto_depIdxs = []int32{
	1, // 0: ztm.v1.PolicyRule.allow:type_name -> ztm.v1.PolicyMatch
	1, // 1: ztm.v1.PolicyRule.deny:type_name -> ztm.v1.PolicyMatch
	0, // 2: ztm.v1.PolicyBundle.rules:type_name -> ztm.v1.PolicyRule
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ztm_v1_policy_proto_init() }
func file_ztm_v1_policy_proto_init() {
	if File_ztm_v1_policy_proto != nil {
		return
	}
	file_ztm_v1_policy_proto_msgTypes[1].OneofWrappers = []any{
		(*PolicyMatch_Service)(nil),
		(*PolicyMatch_Relay)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ztm_v1_policy_proto_rawDesc), len(file_ztm_v1_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ztm_v1_policy_proto_goTypes,
		DependencyIndexes: file_ztm_v1_policy_proto_depIdxs,
		MessageInfos:      file_ztm_v1_policy_proto_msgTypes,
	}.Build()
	File_ztm_v1_policy_proto = out.File
	file_ztm_v1_policy_proto_goTypes = nil
	file_ztm_v1_policy_proto_depIdxs = nil
}
