// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ztm/v1/rpc.proto

package ztmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinClusterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JoinToken     string                 `protobuf:"bytes,1,opt,name=join_token,json=joinToken,proto3" json:"join_token,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	GossipAddr    string                 `protobuf:"bytes,3,opt,name=gossip_addr,json=gossipAddr,proto3" json:"gossip_addr,omitempty"`
	MeshAddr      string                 `protobuf:"bytes,4,opt,name=mesh_addr,json=meshAddr,proto3" json:"mesh_addr,omitempty"`
	ClientAddr    string                 `protobuf:"bytes,5,opt,name=client_addr,json=clientAddr,proto3" json:"client_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinClusterRequest) Reset() {
	*x = JoinClusterRequest{}
	mi := &file_ztm_v1_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinClusterRequest) ProtoMessage() {}

func (x *JoinClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ztm_v1_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinClusterRequest.ProtoReflect.Descriptor instead.
func (*JoinClusterRequest) Descriptor() ([]byte, []int) {
	return file_ztm_v1_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *JoinClusterRequest) GetJoinToken() string {
	if x != nil {
		return x.JoinToken
	}
	return ""
}

func (x *JoinClusterRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *JoinClusterRequest) GetGossipAddr() string {
	if x != nil {
		return x.GossipAddr
	}
	return ""
}

func (x *JoinClusterRequest) GetMeshAddr() string {
	if x != nil {
		return x.MeshAddr
	}
	return ""
}

func (x *JoinClusterRequest) GetClientAddr() string {
	if x != nil {
		return x.ClientAddr
	}
	return ""
}

type JoinClusterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeCertPem   []byte                 `protobuf:"bytes,1,opt,name=node_cert_pem,json=nodeCertPem,proto3" json:"node_cert_pem,omitempty"`
	NodeKeyPem    []byte                 `protobuf:"bytes,2,opt,name=node_key_pem,json=nodeKeyPem,proto3" json:"node_key_pem,omitempty"`
	CaCertPem     []byte                 `protobuf:"bytes,3,opt,name=ca_cert_pem,json=caCertPem,proto3" json:"ca_cert_pem,omitempty"`
	Cluster       string                 `protobuf:"bytes,4,opt,name=cluster,proto3" json:"cluster,omitempty"`
	GossipSecret  []byte                 `protobuf:"bytes,5,opt,name=gossip_secret,json=gossipSecret,proto3" json:"gossip_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinClusterResponse) Reset() {
	*x = JoinClusterResponse{}
	mi := &file_ztm_v1_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinClusterResponse) ProtoMessage() {}

func (x *JoinClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ztm_v1_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinClusterResponse.ProtoReflect.Descriptor instead.
func (*JoinClusterResponse) Descriptor() ([]byte, []int) {
	return file_ztm_v1_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *JoinClusterResponse) GetNodeCertPem() []byte {
	if x != nil {
		return x.NodeCertPem
	}
	return nil
}

func (x *JoinClusterResponse) GetNodeKeyPem() []byte {
	if x != nil {
		return x.NodeKeyPem
	}
	return nil
}

func (x *JoinClusterResponse) GetCaCertPem() []byte {
	if x != nil {
		return x.CaCertPem
	}
	return nil
}

func (x *JoinClusterResponse) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *JoinClusterResponse) GetGossipSecret() []byte {
	if x != nil {
		return x.GossipSecret
	}
	return nil
}

type ResolveServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveServiceRequest) Reset() {
	*x = ResolveServiceRequest{}
	mi := &file_ztm_v1_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveServiceRequest) ProtoMessage() {}

func (x *ResolveServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ztm_v1_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveServiceRequest.ProtoReflect.Descriptor instead.
func (*ResolveServiceRequest) Descriptor() ([]byte, []int) {
	return file_ztm_v1_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *ResolveServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResolveServiceRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type ResolveServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*ServiceAnnouncement `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveServiceResponse) Reset() {
	*x = ResolveServiceResponse{}
	mi := &file_ztm_v1_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveServiceResponse) ProtoMessage() {}

func (x *ResolveServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ztm_v1_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveServiceResponse.ProtoReflect.Descriptor instead.
func (*ResolveServiceResponse) Descriptor() ([]byte, []int) {
	return file_ztm_v1_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *ResolveServiceResponse) GetServices() []*ServiceAnnouncement {
	if x != nil {
		return x.Services
	}
	return nil
}

type PushPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicyBundle  []byte                 `protobuf:"bytes,1,opt,name=policy_bundle,json=policyBundle,proto3" json:"policy_bundle,omitempty"` // serialized PolicyBundle
	MinVersion    uint64                 `protobuf:"varint,2,opt,name=min_version,json=minVersion,proto3" json:"min_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushPolicyRequest) Reset() {
	*x = PushPolicyRequest{}
	mi := &file_ztm_v1_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushPolicyRequest) ProtoMessage() {}

func (x *PushPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ztm_v1_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushPolicyRequest.ProtoReflect.Descriptor instead.
func (*PushPolicyRequest) Descriptor() ([]byte, []int) {
	return file_ztm_v1_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *PushPolicyRequest) GetPolicyBundle() []byte {
	if x != nil {
		return x.PolicyBundle
	}
	return nil
}

func (x *PushPolicyRequest) GetMinVersion() uint64 {
	if x != nil {
		return x.MinVersion
	}
	return 0
}

type PushPolicyResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AcceptedVersion uint64                 `protobuf:"varint,1,opt,name=accepted_version,json=acceptedVersion,proto3" json:"accepted_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PushPolicyResponse) Reset() {
	*x = PushPolicyResponse{}
	mi := &file_ztm_v1_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushPolicyResponse) ProtoMessage() {}

func (x *PushPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ztm_v1_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushPolicyResponse.ProtoReflect.Descriptor instead.
func (*PushPolicyResponse) Descriptor() ([]byte, []int) {
	return file_ztm_v1_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *PushPolicyResponse) GetAcceptedVersion() uint64 {
	if x != nil {
		return x.AcceptedVersion
	}
	return 0
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetNodeId  string                 `protobuf:"bytes,1,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_ztm_v1_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ztm_v1_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_ztm_v1_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *HealthCheckRequest) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reachable     bool                   `protobuf:"varint,1,opt,name=reachable,proto3" json:"reachable,omitempty"`
	LatencyMs     uint32                 `protobuf:"varint,2,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	MeshOk        bool                   `protobuf:"varint,3,opt,name=mesh_ok,json=meshOk,proto3" json:"mesh_ok,omitempty"`
	GossipOk      bool                   `protobuf:"varint,4,opt,name=gossip_ok,json=gossipOk,proto3" json:"gossip_ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_ztm_v1_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ztm_v1_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_ztm_v1_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *HealthCheckResponse) GetReachable() bool {
	if x != nil {
		return x.Reachable
	}
	return false
}

func (x *HealthCheckResponse) GetLatencyMs() uint32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *HealthCheckResponse) GetMeshOk() bool {
	if x != nil {
		return x.MeshOk
	}
	return false
}

func (x *HealthCheckResponse) GetGossipOk() bool {
	if x != nil {
		return x.GossipOk
	}
	return false
}

type RelayStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetNodeId  string                 `protobuf:"bytes,1,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayStatsRequest) Reset() {
	*x = RelayStatsRequest{}
	mi := &file_ztm_v1_rpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayStatsRequest) ProtoMessage() {}

func (x *RelayStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ztm_v1_rpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayStatsRequest.ProtoReflect.Descriptor instead.
func (*RelayStatsRequest) Descriptor() ([]byte, []int) {
	return file_ztm_v1_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *RelayStatsRequest) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

type RelayStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BytesIn       uint64                 `protobuf:"varint,1,opt,name=bytes_in,json=bytesIn,proto3" json:"bytes_in,omitempty"`
	BytesOut      uint64                 `protobuf:"varint,2,opt,name=bytes_out,json=bytesOut,proto3" json:"bytes_out,omitempty"`
	ActiveStreams uint32                 `protobuf:"varint,3,opt,name=active_streams,json=activeStreams,proto3" json:"active_streams,omitempty"`
	ErrorRate     float32                `protobuf:"fixed32,4,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayStatsResponse) Reset() {
	*x = RelayStatsResponse{}
	mi := &file_ztm_v1_rpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayStatsResponse) ProtoMessage() {}

func (x *RelayStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ztm_v1_rpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayStatsResponse.ProtoReflect.Descriptor instead.
func (*RelayStatsResponse) Descriptor() ([]byte, []int) {
	return file_ztm_v1_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *RelayStatsResponse) GetBytesIn() uint64 {
	if x != nil {
		return x.BytesIn
	}
	return 0
}

func (x *RelayStatsResponse) GetBytesOut() uint64 {
	if x != nil {
		return x.BytesOut
	}
	return 0
}

func (x *RelayStatsResponse) GetActiveStreams() uint32 {
	if x != nil {
		return x.ActiveStreams
	}
	return 0
}

func (x *RelayStatsResponse) GetErrorRate() float32 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

var File_ztm_v1_rpc_proto protoreflect.FileDescriptor

const file_ztm_v1_rpc_proto_rawDesc = "" +
	"\n" +
	"\x10ztm/v1/rpc.proto\x12\x06ztm.v1\x1a\x13ztm/v1/gossip.proto\"\xab\x01\n" +
	"\x12JoinClusterRequest\x12\x1d\n" +
	"\n" +
	"join_token\x18\x01 \x01(\tR\tjoinToken\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vgossip_addr\x18\x03 \x01(\tR\n" +
	"gossipAddr\x12\x1b\n" +
	"\tmesh_addr\x18\x04 \x01(\tR\bmeshAddr\x12\x1f\n" +
	"\vclient_addr\x18\x05 \x01(\tR\n" +
	"clientAddr\"\xba\x01\n" +
	"\x13JoinClusterResponse\x12\"\n" +
	"\rnode_cert_pem\x18\x01 \x01(\fR\vnodeCertPem\x12 \n" +
	"\fnode_key_pem\x18\x02 \x01(\fR\n" +
	"nodeKeyPem\x12\x1e\n" +
	"\vca_cert_pem\x18\x03 \x01(\fR\tcaCertPem\x12\x18\n" +
	"\acluster\x18\x04 \x01(\tR\acluster\x12#\n" +
	"\rgossip_secret\x18\x05 \x01(\fR\fgossipSecret\"\xa9\x01\n" +
	"\x15ResolveServiceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12A\n" +
	"\x06labels\x18\x02 \x03(\v2).ztm.v1.ResolveServiceRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Q\n" +
	"\x16ResolveServiceResponse\x127\n" +
	"\bservices\x18\x01 \x03(\v2\x1b.ztm.v1.ServiceAnnouncementR\bservices\"Y\n" +
	"\x11PushPolicyRequest\x12#\n" +
	"\rpolicy_bundle\x18\x01 \x01(\fR\fpolicyBundle\x12\x1f\n" +
	"\vmin_version\x18\x02 \x01(\x04R\n" +
	"minVersion\"?\n" +
	"\x12PushPolicyResponse\x12)\n" +
	"\x10accepted_version\x18\x01 \x01(\x04R\x0facceptedVersion\":\n" +
	"\x12HealthCheckRequest\x12$\n" +
	"\x0etarget_node_id\x18\x01 \x01(\tR\ftargetNodeId\"\x88\x01\n" +
	"\x13HealthCheckResponse\x12\x1c\n" +
	"\treachable\x18\x01 \x01(\bR\treachable\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x02 \x01(\rR\tlatencyMs\x12\x17\n" +
	"\amesh_ok\x18\x03 \x01(\bR\x06meshOk\x12\x1b\n" +
	"\tgossip_ok\x18\x04 \x01(\bR\bgossipOk\"9\n" +
	"\x11RelayStatsRequest\x12$\n" +
	"\x0etarget_node_id\x18\x01 \x01(\tR\ftargetNodeId\"\x92\x01\n" +
	"\x12RelayStatsResponse\x12\x19\n" +
	"\bbytes_in\x18\x01 \x01(\x04R\abytesIn\x12\x1b\n" +
	"\tbytes_out\x18\x02 \x01(\x04R\bbytesOut\x12%\n" +
	"\x0eactive_streams\x18\x03 \x01(\rR\ractiveStreams\x12\x1d\n" +
	"\n" +
	"error_rate\x18\x04 \x01(\x02R\terrorRate2\xf8\x02\n" +
	"\vNodeService\x12F\n" +
	"\vJoinCluster\x12\x1a.ztm.v1.JoinClusterRequest\x1a\x1b.ztm.v1.JoinClusterResponse\x12O\n" +
	"\x0eResolveService\x12\x1d.ztm.v1.ResolveServiceRequest\x1a\x1e.ztm.v1.ResolveServiceResponse\x12C\n" +
	"\n" +
	"PushPolicy\x12\x19.ztm.v1.PushPolicyRequest\x1a\x1a.ztm.v1.PushPolicyResponse\x12F\n" +
	"\vHealthCheck\x12\x1a.ztm.v1.HealthCheckRequest\x1a\x1b.ztm.v1.HealthCheckResponse\x12C\n" +
	"\n" +
	"RelayStats\x12\x19.ztm.v1.RelayStatsRequest\x1a\x1a.ztm.v1.RelayStatsResponseB\x1cZ\x1aztm/api/proto/ztm/v1;ztmv1b\x06proto3"

var (
	file_ztm_v1_rpc_proto_rawDescOnce sync.Once
	file_ztm_v1_rpc_proto_rawDescData []byte
)

func file_ztm_v1_rpc_proto_rawDescGZIP() []byte {
	file_ztm_v1_rpc_proto_rawDescOnce.Do(func() {
		file_ztm_v1_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ztm_v1_rpc_proto_rawDesc), len(file_ztm_v1_rpc_proto_rawDesc)))
	})
	return file_ztm_v1_rpc_proto_rawDescData
}

var file_ztm_v1_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_ztm_v1_rpc_proto_goTypes = []any{
	(*JoinClusterRequest)(nil),     // 0: ztm.v1.JoinClusterRequest
	(*JoinClusterResponse)(nil),    // 1: ztm.v1.JoinClusterResponse
	(*ResolveServiceRequest)(nil),  // 2: ztm.v1.ResolveServiceRequest
	(*ResolveServiceResponse)(nil), // 3: ztm.v1.ResolveServiceResponse
	(*PushPolicyRequest)(nil),      // 4: ztm.v1.PushPolicyRequest
	(*PushPolicyResponse)(nil),     // 5: ztm.v1.PushPolicyResponse
	(*HealthCheckRequest)(nil),     // 6: ztm.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),    // 7: ztm.v1.HealthCheckResponse
	(*RelayStatsRequest)(nil),      // 8: ztm.v1.RelayStatsRequest
	(*RelayStatsResponse)(nil),     // 9: ztm.v1.RelayStatsResponse
	nil,                            // 10: ztm.v1.ResolveServiceRequest.LabelsEntry
	(*ServiceAnnouncement)(nil),    // 11: ztm.v1.ServiceAnnouncement
}
var file_ztm_v1_rpc_proto_depIdxs = []int32{
	10, // 0: ztm.v1.ResolveServiceRequest.labels:type_name -> ztm.v1.ResolveServiceRequest.LabelsEntry
	11, // 1: ztm.v1.ResolveServiceResponse.services:type_name -> ztm.v1.ServiceAnnouncement
	0,  // 2: ztm.v1.NodeService.JoinCluster:input_type -> ztm.v1.JoinClusterRequest
	2,  // 3: ztm.v1.NodeService.ResolveService:input_type -> ztm.v1.ResolveServiceRequest
	4,  // 4: ztm.v1.NodeService.PushPolicy:input_type -> ztm.v1.PushPolicyRequest
	6,  // 5: ztm.v1.NodeService.HealthCheck:input_type -> ztm.v1.HealthCheckRequest
	8,  // 6: ztm.v1.NodeService.RelayStats:input_type -> ztm.v1.RelayStatsRequest
	1,  // 7: ztm.v1.NodeService.JoinCluster:output_type -> ztm.v1.JoinClusterResponse
	3,  // 8: ztm.v1.NodeService.ResolveService:output_type -> ztm.v1.ResolveServiceResponse
	5,  // 9: ztm.v1.NodeService.PushPolicy:output_type -> ztm.v1.PushPolicyResponse
	7,  // 10: ztm.v1.NodeService.HealthCheck:output_type -> ztm.v1.HealthCheckResponse
	9,  // 11: ztm.v1.NodeService.RelayStats:output_type -> ztm.v1.RelayStatsResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_ztm_v1_rpc_proto_init() }
func file_ztm_v1_rpc_proto_init() {
	if File_ztm_v1_rpc_proto != nil {
		return
	}
	file_ztm_v1_gossip_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ztm_v1_rpc_proto_rawDesc), len(file_ztm_v1_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ztm_v1_rpc_proto_goTypes,
		DependencyIndexes: file_ztm_v1_rpc_proto_depIdxs,
		MessageInfos:      file_ztm_v1_rpc_proto_msgTypes,
	}.Build()
	File_ztm_v1_rpc_proto = out.File
	file_ztm_v1_rpc_proto_goTypes = nil
	file_ztm_v1_rpc_proto_depIdxs = nil
}
