// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ztm/v1/tunnel.proto

package ztmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Data plane framing over QUIC streams.
type TunnelFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*TunnelFrame_Connect
	//	*TunnelFrame_ConnectAck
	//	*TunnelFrame_Data
	//	*TunnelFrame_Close
	//	*TunnelFrame_Ping
	Frame         isTunnelFrame_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelFrame) Reset() {
	*x = TunnelFrame{}
	mi := &file_ztm_v1_tunnel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelFrame) ProtoMessage() {}

func (x *TunnelFrame) ProtoReflect() protoreflect.Message {
	mi := &file_ztm_v1_tunnel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelFrame.ProtoReflect.Descriptor instead.
func (*TunnelFrame) Descriptor() ([]byte, []int) {
	return file_ztm_v1_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *TunnelFrame) GetFrame() isTunnelFrame_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *TunnelFrame) GetConnect() *ConnectRequest {
	if x != nil {
		if x, ok := x.Frame.(*TunnelFrame_Connect); ok {
			return x.Connect
		}
	}
	return nil
}

func (x *TunnelFrame) GetConnectAck() *ConnectResponse {
	if x != nil {
		if x, ok := x.Frame.(*TunnelFrame_ConnectAck); ok {
			return x.ConnectAck
		}
	}
	return nil
}

func (x *TunnelFrame) GetData() *DataPayload {
	if x != nil {
		if x, ok := x.Frame.(*TunnelFrame_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *TunnelFrame) GetClose() *CloseNotify {
	if x != nil {
		if x, ok := x.Frame.(*TunnelFrame_Close); ok {
			return x.Close
		}
	}
	return nil
}

func (x *TunnelFrame) GetPing() *PingFrame {
	if x != nil {
		if x, ok := x.Frame.(*TunnelFrame_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isTunnelFrame_Frame interface {
	isTunnelFrame_Frame()
}

type TunnelFrame_Connect struct {
	Connect *ConnectRequest `protobuf:"bytes,1,opt,name=connect,proto3,oneof"`
}

type TunnelFrame_ConnectAck struct {
	ConnectAck *ConnectResponse `protobuf:"bytes,2,opt,name=connect_ack,json=connectAck,proto3,oneof"`
}

type TunnelFrame_Data struct {
	Data *DataPayload `protobuf:"bytes,3,opt,name=data,proto3,oneof"`
}

type TunnelFrame_Close struct {
	Close *CloseNotify `protobuf:"bytes,4,opt,name=close,proto3,oneof"`
}

type TunnelFrame_Ping struct {
	Ping *PingFrame `protobuf:"bytes,5,opt,name=ping,proto3,oneof"`
}

func (*TunnelFrame_Connect) isTunnelFrame_Frame() {}

func (*TunnelFrame_ConnectAck) isTunnelFrame_Frame() {}

func (*TunnelFrame_Data) isTunnelFrame_Frame() {}

func (*TunnelFrame_Close) isTunnelFrame_Frame() {}

func (*TunnelFrame_Ping) isTunnelFrame_Frame() {}

type ConnectRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetService  string                 `protobuf:"bytes,1,opt,name=target_service,json=targetService,proto3" json:"target_service,omitempty"`
	TargetHost     string                 `protobuf:"bytes,2,opt,name=target_host,json=targetHost,proto3" json:"target_host,omitempty"`
	TargetPort     uint32                 `protobuf:"varint,3,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
	ClientIdentity string                 `protobuf:"bytes,4,opt,name=client_identity,json=clientIdentity,proto3" json:"client_identity,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_ztm_v1_tunnel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ztm_v1_tunnel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_ztm_v1_tunnel_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectRequest) GetTargetService() string {
	if x != nil {
		return x.TargetService
	}
	return ""
}

func (x *ConnectRequest) GetTargetHost() string {
	if x != nil {
		return x.TargetHost
	}
	return ""
}

func (x *ConnectRequest) GetTargetPort() uint32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

func (x *ConnectRequest) GetClientIdentity() string {
	if x != nil {
		return x.ClientIdentity
	}
	return ""
}

type ConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	ResolvedNode  string                 `protobuf:"bytes,3,opt,name=resolved_node,json=resolvedNode,proto3" json:"resolved_node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_ztm_v1_tunnel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ztm_v1_tunnel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_ztm_v1_tunnel_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ConnectResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ConnectResponse) GetResolvedNode() string {
	if x != nil {
		return x.ResolvedNode
	}
	return ""
}

type DataPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Fin           bool                   `protobuf:"varint,2,opt,name=fin,proto3" json:"fin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataPayload) Reset() {
	*x = DataPayload{}
	mi := &file_ztm_v1_tunnel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPayload) ProtoMessage() {}

func (x *DataPayload) ProtoReflect() protoreflect.Message {
	mi := &file_ztm_v1_tunnel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPayload.ProtoReflect.Descriptor instead.
func (*DataPayload) Descriptor() ([]byte, []int) {
	return file_ztm_v1_tunnel_proto_rawDescGZIP(), []int{3}
}

func (x *DataPayload) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DataPayload) GetFin() bool {
	if x != nil {
		return x.Fin
	}
	return false
}

type CloseNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseNotify) Reset() {
	*x = CloseNotify{}
	mi := &file_ztm_v1_tunnel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseNotify) ProtoMessage() {}

func (x *CloseNotify) ProtoReflect() protoreflect.Message {
	mi := &file_ztm_v1_tunnel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseNotify.ProtoReflect.Descriptor instead.
func (*CloseNotify) Descriptor() ([]byte, []int) {
	return file_ztm_v1_tunnel_proto_rawDescGZIP(), []int{4}
}

func (x *CloseNotify) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type PingFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingFrame) Reset() {
	*x = PingFrame{}
	mi := &file_ztm_v1_tunnel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingFrame) ProtoMessage() {}

func (x *PingFrame) ProtoReflect() protoreflect.Message {
	mi := &file_ztm_v1_tunnel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingFrame.ProtoReflect.Descriptor instead.
func (*PingFrame) Descriptor() ([]byte, []int) {
	return file_ztm_v1_tunnel_proto_rawDescGZIP(), []int{5}
}

func (x *PingFrame) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

var File_ztm_v1_tunnel_proto protoreflect.FileDescriptor

const file_ztm_v1_tunnel_proto_rawDesc = "" +
	"\n" +
	"\x13ztm/v1/tunnel.proto\x12\x06ztm.v1\"\x87\x02\n" +
	"\vTunnelFrame\x122\n" +
	"\aconnect\x18\x01 \x01(\v2\x16.ztm.v1.ConnectRequestH\x00R\aconnect\x12:\n" +
	"\vconnect_ack\x18\x02 \x01(\v2\x17.ztm.v1.ConnectResponseH\x00R\n" +
	"connectAck\x12)\n" +
	"\x04data\x18\x03 \x01(\v2\x13.ztm.v1.DataPayloadH\x00R\x04data\x12+\n" +
	"\x05close\x18\x04 \x01(\v2\x13.ztm.v1.CloseNotifyH\x00R\x05close\x12'\n" +
	"\x04ping\x18\x05 \x01(\v2\x11.ztm.v1.PingFrameH\x00R\x04pingB\a\n" +
	"\x05frame\"\xa2\x01\n" +
	"\x0eConnectRequest\x12%\n" +
	"\x0etarget_service\x18\x01 \x01(\tR\rtargetService\x12\x1f\n" +
	"\vtarget_host\x18\x02 \x01(\tR\n" +
	"targetHost\x12\x1f\n" +
	"\vtarget_port\x18\x03 \x01(\rR\n" +
	"targetPort\x12'\n" +
	"\x0fclient_identity\x18\x04 \x01(\tR\x0eclientIdentity\"^\n" +
	"\x0fConnectResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12#\n" +
	"\rresolved_node\x18\x03 \x01(\tR\fresolvedNode\"3\n" +
	"\vDataPayload\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x10\n" +
	"\x03fin\x18\x02 \x01(\bR\x03fin\"%\n" +
	"\vCloseNotify\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\x1d\n" +
	"\tPingFrame\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seqB\x1cZ\x1aztm/api/proto/ztm/v1;ztmv1b\x06proto3"

var (
	file_ztm_v1_tunnel_proto_rawDescOnce sync.Once
	file_ztm_v1_tunnel_proto_rawDescData []byte
)

func file_ztm_v1_tunnel_proto_rawDescGZIP() []byte {
	file_ztm_v1_tunnel_proto_rawDescOnce.Do(func() {
		file_ztm_v1_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ztm_v1_tunnel_proto_rawDesc), len(file_ztm_v1_tunnel_proto_rawDesc)))
	})
	return file_ztm_v1_tunnel_proto_rawDescData
}

var file_ztm_v1_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_ztm_v1_tunnel_proto_goTypes = []any{
	(*TunnelFrame)(nil),     // 0: ztm.v1.TunnelFrame
	(*ConnectRequest)(nil),  // 1: ztm.v1.ConnectRequest
	(*ConnectResponse)(nil), // 2: ztm.v1.ConnectResponse
	(*DataPayload)(nil),     // 3: ztm.v1.DataPayload
	(*CloseNotify)(nil),     // 4: ztm.v1.CloseNotify
	(*PingFrame)(nil),       // 5: ztm.v1.PingFrame
}
var file_ztm_v1_tunnel_proto_depIdxs = []int32{
	1, // 0: ztm.v1.TunnelFrame.connect:type_name -> ztm.v1.ConnectRequest
	2, // 1: ztm.v1.TunnelFrame.connect_ack:type_name -> ztm.v1.ConnectResponse
	3, // 2: ztm.v1.TunnelFrame.data:type_name -> ztm.v1.DataPayload
	4, // 3: ztm.v1.TunnelFrame.close:type_name -> ztm.v1.CloseNotify
	5, // 4: ztm.v1.TunnelFrame.ping:type_name -> ztm.v1.PingFrame
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_ztm_v1_tunnel_proto_init() }
func file_ztm_v1_tunnel_proto_init() {
	if File_ztm_v1_tunnel_proto != nil {
		return
	}
	file_ztm_v1_tunnel_proto_msgTypes[0].OneofWrappers = []any{
		(*TunnelFrame_Connect)(nil),
		(*TunnelFrame_ConnectAck)(nil),
		(*TunnelFrame_Data)(nil),
		(*TunnelFrame_Close)(nil),
		(*TunnelFrame_Ping)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ztm_v1_tunnel_proto_rawDesc), len(file_ztm_v1_tunnel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ztm_v1_tunnel_proto_goTypes,
		DependencyIndexes: file_ztm_v1_tunnel_proto_depIdxs,
		MessageInfos:      file_ztm_v1_tunnel_proto_msgTypes,
	}.Build()
	File_ztm_v1_tunnel_proto = out.File
	file_ztm_v1_tunnel_proto_goTypes = nil
	file_ztm_v1_tunnel_proto_depIdxs = nil
}
